import { useRouter } from "next/router";
import { useState } from "react";
const data = [
  {
    id: 1,
    Name: "Sneakers",
    Image: "/zurg1.jpg",
    Color: "White",
    Accessories: "Extra laces",
    Price: "120,000₮",
    Stock: 10,
  },
  {
    id: 2,
    Name: "Pants",
    Image: "/zurg2.jpg",
    Color: "Black",
    Accessories: "Belt",
    Price: "85,000₮",
    Stock: 5,
  },
  {
    id: 3,
    Name: "T-shirt",
    Image: "/zurg3.jpg",
    Color: "Blue",
    Accessories: "Sticker",
    Price: "35,000₮",
    Stock: 20,
  },
  {
    id: 4,
    Name: "Hoodie",
    Image: "/zurg4.jpg",
    Color: "Gray",
    Accessories: "Keychain",
    Price: "65,000₮",
    Stock: 12,
  },
  {
    id: 5,
    Name: "Skirt",
    Image: "/zurg5.jpg",
    Color: "Pink",
    Accessories: "Chain",
    Price: "55,000₮",
    Stock: 7,
  },
  {
    id: 6,
    Name: "Skirt",
    Image: "/zurg6.jpg",
    Color: "Pink",
    Accessories: "Chain",
    Price: "55,000₮",
    Stock: 7,
  },
  {
    id: 7,
    Name: "Skirt",
    Image: "/zurg7.jpg",
    Color: "Pink",
    Accessories: "Chain",
    Price: "55,000₮",
    Stock: 7,
  },
  {
    id: 8,
    Name: "Skirt",
    Image: "/zurg8.jpg",
    Color: "Pink",
    Accessories: "Chain",
    Price: "55,000₮",
    Stock: 7,
  },
];
